// Generate exact facelet permutations for all 18 moves from cubejs's cubie
// model (URFDLB). Writes src/engine/moves.generated.js. Guaranteed correct
// within-face, unlike color-only comparison from a solved cube.
import CubeJS from 'cubejs';
import { writeFileSync } from 'node:fs';

const FACES = ['U', 'R', 'F', 'D', 'L', 'B'];
const SOLVED = 'UUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBB';

// Standard Kociemba facelet tables.
const cornerFacelet = [
  [8, 9, 20], [6, 18, 38], [0, 36, 47], [2, 45, 11],
  [29, 26, 15], [27, 44, 24], [33, 53, 42], [35, 17, 51],
];
const edgeFacelet = [
  [5, 10], [7, 19], [3, 37], [1, 46], [32, 16], [28, 25],
  [30, 43], [34, 52], [23, 12], [21, 41], [50, 39], [48, 14],
];
const centerFacelet = [4, 13, 22, 31, 40, 49];

// Build the facelet permutation induced by a cube's cubie state (relative to solved).
// perm[dest] = source, i.e. newState[dest] = oldState[source].
function faceletPerm(c) {
  const perm = new Array(54).fill(-1);
  for (let i = 0; i < 8; i++) {
    const j = c.cp[i], ori = c.co[i];
    for (let k = 0; k < 3; k++) {
      const dest = cornerFacelet[i][(k + ori) % 3];
      const source = cornerFacelet[j][k];
      perm[dest] = source;
    }
  }
  for (let i = 0; i < 12; i++) {
    const j = c.ep[i], ori = c.eo[i];
    for (let k = 0; k < 2; k++) {
      const dest = edgeFacelet[i][(k + ori) % 2];
      const source = edgeFacelet[j][k];
      perm[dest] = source;
    }
  }
  for (const f of centerFacelet) perm[f] = f;
  return perm;
}

// Validate: a solved cube must reconstruct to identity perm -> SOLVED string.
const solvedPerm = faceletPerm(new CubeJS());
if (solvedPerm.some((v, i) => v !== i)) {
  console.error('TABLE ERROR: solved cube did not yield identity perm');
  process.exit(1);
}

const MOVES = [];
for (const f of FACES) for (const suf of ['', "'", '2']) MOVES.push(f + suf);

const PERMS = {};
let mismatch = 0;
for (const m of MOVES) {
  const c = new CubeJS();
  c.move(m);
  const perm = faceletPerm(c);
  PERMS[m] = perm;
  // Cross-check color-level against cubejs asString.
  const mine = perm.map((s) => SOLVED[s]).join('');
  if (mine !== c.asString()) { mismatch++; console.error('color mismatch on', m); }
}
if (mismatch) process.exit(1);

const out =
  '// AUTO-GENERATED by scripts/gen-moves.mjs — do not edit by hand.\n' +
  '// Exact facelet permutations for all 18 moves (perm[dest] = source).\n' +
  'export const PERMS = ' + JSON.stringify(PERMS) + ';\n';
writeFileSync(new URL('../src/engine/moves.generated.js', import.meta.url), out);
console.log('Wrote moves.generated.js — 18 moves, tables validated ✓');
